name: CI

on:
  workflow_dispatch:
    branches:
      - npm
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install and build
        run: yarn install

      - name: build
        run: yarn build

      - name: Publish package on NPM 📦
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

